wxpay.appId=wx8eb6df2b696e3e39
wxpay.appSecret=644a855a66e5d0717946500074feb272
wxpay.mchId=1632349884
wxpay.partnerKey=asdfasdfaw23asdfdfsdfgsdfgsdfgsd
wxpay.certPath=/www/wwwroot/qkl/xllg/cert/apiclient_cert.p12
#wxpay.certPath=D:/cert/qkl/apiclient_cert.p12
wxpay.domain=https://lgapi.qinkonglan.cn/
