v3.appId=wx8eb6df2b696e3e39
v3.keyPath=/www/wwwroot/qkl/xllg/cert/apiclient_key.pem
v3.certPath=/www/wwwroot/qkl/xllg/cert/apiclient_cert.pem
v3.certP12Path=/www/wwwroot/qkl/xllg/cert/apiclient_cert.p12
v3.platformCertPath=/www/wwwroot/qkl/xllg/cert/wx_cert.pem
v3.mchId=1632349884
v3.apiKey3=aw2e3asdfasdfasdfe3rsfdsfasdfasd
v3.apiKey=asdfasdfaw23asdfdfsdfgsdfgsdfgsd
v3.domain=https://lgapi.qinkonglan.cn/

#v3.appId=wx8eb6df2b696e3e39
#v3.keyPath=D:/cert/qkl/apiclient_key.pem
#v3.certPath=D:/cert/qkl/apiclient_cert.pem
#v3.certP12Path=D:/cert/qkl/apiclient_cert.p12
#v3.platformCertPath=D:/cert/qkl/wx_cert.pem
#v3.mchId=1632349884
#v3.apiKey3=aw2e3asdfasdfasdfe3rsfdsfasdfasd
#v3.apiKey=asdfasdfaw23asdfdfsdfgsdfgsdfgsd
#v3.domain=https://lgapi.qinkonglan.cn/
